version: "3"

services:
  app:
    container_name: work
    restart: always
    build:
      context: .
    ports:
      - "80:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
    environment:
      DIDYOUSEE: Hello-world
    stdin_open: true
  api:
    container_name: api
    build: ./NumerController/server
    ports:
      - '8080:8080'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'